"""new columns to opencv

Revision ID: cfae264b4745
Revises: 4da0de5d7d7a
Create Date: 2025-12-08 23:28:05.293717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfae264b4745'
down_revision: Union[str, Sequence[str], None] = '4da0de5d7d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('marker_id', sa.Integer(), nullable=True))
    op.add_column('instruments', sa.Column('marker_image_path', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_instruments_marker_id'), 'instruments', ['marker_id'], unique=True)
    op.add_column('scenarios', sa.Column('initial_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'initial_state')
    op.drop_index(op.f('ix_instruments_marker_id'), table_name='instruments')
    op.drop_column('instruments', 'marker_image_path')
    op.drop_column('instruments', 'marker_id')
    # ### end Alembic commands ###
