"""new columns in the tables

Revision ID: daee1a163be5
Revises: f2cef9a8f28e
Create Date: 2025-12-02 03:24:21.755663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daee1a163be5'
down_revision: Union[str, Sequence[str], None] = 'f2cef9a8f28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('instrument_type', sa.String(length=100), nullable=False))
    op.add_column('instruments', sa.Column('is_container', sa.Boolean(), nullable=False))
    op.add_column('instruments', sa.Column('allowed_physical_states', sa.String(length=255), nullable=True))
    op.add_column('scenario_steps', sa.Column('source_container_name', sa.String(length=100), nullable=True))
    op.add_column('scenario_steps', sa.Column('target_container_name', sa.String(length=100), nullable=True))
    op.add_column('scenario_steps', sa.Column('amount_value', sa.Float(), nullable=True))
    op.add_column('scenario_steps', sa.Column('amount_unit', sa.String(length=20), nullable=True))
    op.drop_column('scenario_steps', 'target_container')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_steps', sa.Column('target_container', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('scenario_steps', 'amount_unit')
    op.drop_column('scenario_steps', 'amount_value')
    op.drop_column('scenario_steps', 'target_container_name')
    op.drop_column('scenario_steps', 'source_container_name')
    op.drop_column('instruments', 'allowed_physical_states')
    op.drop_column('instruments', 'is_container')
    op.drop_column('instruments', 'instrument_type')
    # ### end Alembic commands ###
